/**
 * ✅ EDITABLE FILE - AI Can Modify Values Here
 * 
 * Category Configuration Content
 * This file contains all category definitions for the site
 * 
 * AUTO-GENERATED by Site Builder Template Generator
 * Generated: 2025-12-22T19:14:16.169Z
 */

import type { Category } from './categories.schema'

/**
 * Blog categories with nested subcategories
 * Auto-populated from brand database (BrandCategory table)
 */
export const categories: Category[] = [
  {
    id: "40083ad5-5dad-420a-b0d6-112e8cc909e6",
    name: "Cardio Machines",
    slug: "cardio-machines",
    showInHeader: true,
    showInFooter: true,
    subcategories: [
      {
        id: "f00a4f78-1feb-4cc2-9b36-6b7fb98eec86",
        name: "Treadmills",
        slug: "treadmills",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "460b8379-f202-4613-8cac-ff377019a116",
        name: "Ellipticals",
        slug: "ellipticals",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "1148be08-f5ba-4959-9712-87ae70099a2d",
        name: "Rowing Machines",
        slug: "rowing-machines",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "2bcba199-63e4-4915-980e-dfcdc8cd67e2",
        name: "Exercise Bikes",
        slug: "exercise-bikes",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "beb11fe1-b7c4-469e-ba1f-cd3c470f9041",
        name: "Compact Machines",
        slug: "compact-machines",
        showInHeader: true,
        showInFooter: true
      }
    ]
  },
  {
    id: "f1b787f0-5ffd-4a5d-b4f2-166cb9e517ab",
    name: "Strength Equipment",
    slug: "strength-equipment",
    showInHeader: true,
    showInFooter: true,
    subcategories: [
      {
        id: "3e0fd3f7-d7c5-42f4-b113-d92ef14f1d70",
        name: "Dumbbells",
        slug: "dumbbells",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "4e7121ab-2cef-4568-821e-9bd837d1b268",
        name: "Kettlebells",
        slug: "kettlebells",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "88d6d64c-f403-4d93-ad37-5f376efb560d",
        name: "Weight Benches",
        slug: "weight-benches",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "11aa6171-d5b2-4741-b362-513353f2e9c5",
        name: "Smith Machines",
        slug: "smith-machines",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "85e76353-d69d-4ab1-ba74-105aa129409b",
        name: "Cable Machines",
        slug: "cable-machines",
        showInHeader: true,
        showInFooter: true
      }
    ]
  },
  {
    id: "af349d3d-65f8-4ea9-90da-0e8a659257cd",
    name: "Fitness Accessories",
    slug: "fitness-accessories",
    showInHeader: true,
    showInFooter: true,
    subcategories: [
      {
        id: "d384f135-ef87-460f-81d6-fbf0a61d7b88",
        name: "Running Shoes",
        slug: "running-shoes",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "d6786ea4-f099-4e4a-9def-22b7b7720fd4",
        name: "Workout Apps",
        slug: "workout-apps",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "200ba77b-41d0-4540-9d3e-32efba9c74e6",
        name: "Smart Home Gym Equipment",
        slug: "smart-home-gym-equipment",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "ee4b20fe-7e7e-4597-97fb-75e40787d886",
        name: "Fitness Gifts",
        slug: "fitness-gifts",
        showInHeader: true,
        showInFooter: true
      }
    ]
  },
  {
    id: "10b09695-2b10-4b01-9c59-2cb452b3978c",
    name: "Nutrition and Supplements",
    slug: "nutrition-and-supplements",
    showInHeader: true,
    showInFooter: true,
    subcategories: [
      {
        id: "060af16e-37bc-4fca-8428-879dd8cf74e1",
        name: "Protein Powders",
        slug: "protein-powders",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "b3fb6e79-fd94-4d3b-b77b-51524bb4e737",
        name: "Creatine",
        slug: "creatine",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "c24bfc99-8ae9-4344-8fa0-f19c10084832",
        name: "Cold Plunge Tubs",
        slug: "cold-plunge-tubs",
        showInHeader: true,
        showInFooter: true
      }
    ]
  }
]
