/**
 * ✅ EDITABLE FILE - AI Can Modify Values Here
 * 
 * Site Configuration Content
 * This file contains all customizable values for the site
 * 
 * AUTO-GENERATED by Site Builder Template Generator
 * Brand: Garage Gainz
 * Generated: 2025-12-22T19:14:16.169Z
 */

import type { SiteConfigSchema, ColorConfigSchema } from './config.schema'

/**
 * Main site configuration
 * Values auto-populated from brand database
 */
export const siteContent: SiteConfigSchema = {
  // Brand identity
  brand: {
    id: "9fd4b578-3692-4b69-b483-1fc03df33be7",
    name: "Garage Gainz",
    description: "Fit Gear Insights delivers expert reviews and curated guides to empower fitness enthusiasts in choosing the best equipment and accessories for their home gyms.",
    url: "https://garage-gainz-blog.vercel.app",
    logoPath: "/logo.jpg",
    faviconPath: "/logo.jpg",
    ogImagePath: "/logo.jpg",
    mainAppUrl: "https://app.thefaceless.ai",
    legalEmail: "support@banedigital.com",
    privacyEmail: "support@banedigital.com",
    tagline: "Transform your space with expert home gym gear advice"
  },

  // Homepage hero section
  hero: {
    title: "Welcome to Garage Gainz",
    subtitle: "Transform your space with expert home gym gear advice"
  },

  // Default author information
  author: {
    name: "Garage Gainz Team",
    bio: "Fit Gear Insights delivers expert reviews and curated guides to empower fitness enthusiasts in choosing the best equipment and accessories for thei...",
    role: "Content Creator",
    image: "/logo.jpg"
  },

  // Section headings throughout the site
  sections: {
    topArticles: {
      title: "Featured Articles",
      description: "Handpicked posts just for you"
    },
    recentPosts: {
      title: "Latest Posts"
    },
    categories: {
      title: "Explore Home Fitness Equipment Topics"
    }
  },

  // Newsletter subscription section
  newsletter: {
    title: "Stay Updated",
    description: "Get the latest from Garage Gainz delivered to your inbox",
    disclaimer: "Unsubscribe anytime. We respect your privacy."
  },

  // Blog categories (from brand database)
  categories: [
    { 
      name: "Treadmills",
      icon: "FileText",
      slug: "treadmills"
    },
    { 
      name: "Cardio Machines",
      icon: "FileText",
      slug: "cardio-machines"
    },
    { 
      name: "Running Shoes",
      icon: "FileText",
      slug: "running-shoes"
    },
    { 
      name: "Dumbbells",
      icon: "FileText",
      slug: "dumbbells"
    },
    { 
      name: "Protein Powders",
      icon: "FileText",
      slug: "protein-powders"
    },
    { 
      name: "Kettlebells",
      icon: "FileText",
      slug: "kettlebells"
    }
  ],

  // All authors for this brand (with AI-generated portraits)
  authors: [
    {
      id: "8d6ca7dc-60c8-42b7-b346-5cde5710ef39",
      name: "Samira Patel",
      bio: "With a journalistic flair and a passion for fitness, Samira crafts compelling narratives that not only inform but also inspire. Her expertise in health and wellness enables her to connect with readers on a personal level, providing insightful recommendations and engaging stories that highlight the latest trends and innovations in the fitness world.",
      image: "/authors/8d6ca7dc-60c8-42b7-b346-5cde5710ef39.jpg",
      role: "Health & Fitness Writer"
    },
    {
      id: "d2fd45ba-e844-4d8c-88d9-80af093d5334",
      name: "Avery Chen",
      bio: "Avery combines a meticulous attention to detail with a deep understanding of sports science to provide evidence-based reviews and guides. Their analytical approach ensures readers receive thoroughly researched content, while their clear and concise writing style helps demystify technical aspects of fitness gear, making it easier for enthusiasts to make informed decisions.",
      image: "/authors/d2fd45ba-e844-4d8c-88d9-80af093d5334.jpg",
      role: "Sports Scientist & Gear Analyst"
    },
    {
      id: "ce59784e-53e2-41a0-ba36-8c0c4d67952e",
      name: "Jordan Michaels",
      bio: "Jordan is a dynamic and engaging writer with a knack for breaking down complex fitness equipment features into easy-to-understand language. They blend their extensive experience as a personal trainer with a passion for testing the latest gear, offering readers practical advice with a touch of humor to make fitness accessible to everyone.",
      image: "/authors/ce59784e-53e2-41a0-ba36-8c0c4d67952e.jpg",
      role: "Certified Personal Trainer & Fitness Equipment Specialist"
    }
  ]
}

/**
 * Color configuration
 * Brand colors in oklch() format for consistent rendering
 * Auto-converted from brand hex colors
 */
export const colorContent: ColorConfigSchema = {
  // Light mode colors
  light: {
    primary: "#2563EB",      // #2563EB
    secondary: "#64748B",  // #64748B
    accent: "#F59E0B"         // #F59E0B
  },

  // Dark mode colors (auto-lightened for contrast)
  dark: {
    primary: "#2563EB",
    secondary: "#64748B",
    accent: "#F59E0B"
  }
}
